=== FabricatorsGuild/FG.AutoLogger/src/CodeEffect.Diagnostics.EventSourceGenerator.Schema/CodeEffect.Diagnostics.EventSourceGenerator.Model.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "EventSourceModel",
  "additionalProperties": false,
  "properties": {
    "Loggers": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "#/definitions/LoggerModel"
      }
    },
    "Name": {
      "type": [
        "null",
        "string"
      ]
    },
    "ProviderName": {
      "type": [
        "null",
        "string"
      ]
    },
    "Keywords": {
      "type": [
        "array",
        "string"
      ],
      "items": {
        "$ref": "#/definitions/KeywordModel"
      }
    },
    "TypeTemplates": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "#/definitions/TypeTemplateModel"
      }
    },
    "Events": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "#/definitions/EventModel"
      }
    },
    "Settings": {
      "oneOf": [
        {
          "$ref": "#/definitions/EventSourceSettings"
        },
        {
          "type": "null"
        }
      ]
    }
  },
  "definitions": {
    "LoggerModel": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "Name": {
          "type": [
            "null",
            "string"
          ]
        },
        "StartId": {
          "type": [
            "integer",
            "null"
          ],
          "format": "int32"
        },
        "ImplicitArguments": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/EventArgumentModel"
          }
        },
        "OverrideArguments": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/EventArgumentModel"
          }
        }
      }
    },
    "EventArgumentModel": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "Name": {
          "type": [
            "null",
            "string"
          ]
        },
        "Type": {
          "type": [
            "null",
            "string"
          ]
        },
        "Assignment": {
          "type": [
            "null",
            "string"
          ]
        },
        "TypeTemplate": {
          "oneOf": [
            {
              "$ref": "#/definitions/TypeTemplateModel"
            },
            {
              "type": "null"
            }
          ]
        }
      }
    },
    "TypeTemplateModel": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "Name": {
          "type": [
            "null",
            "string"
          ]
        },
        "CLRType": {
          "type": [
            "null",
            "string"
          ]
        },
        "Arguments": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/EventArgumentModel"
          }
        }
      }
    },
    "KeywordModel": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "Name": {
          "type": [
            "null",
            "string"
          ]
        },
        "Value": {
          "type": [
            "integer",
            "null"
          ],
          "format": "int32"
        }
      }
    },
    "EventModel": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "Id": {
          "type": [
            "integer",
            "null"
          ],
          "format": "int32"
        },
        "Name": {
          "type": [
            "null",
            "string"
          ]
        },
        "Arguments": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/EventArgumentModel"
          }
        },
        "Level": {
          "oneOf": [
            {
              "$ref": "#/definitions/EventLevel"
            }
          ]
        },
        "Keywords": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/KeywordModel"
          }
        },
        "MessageFormatter": {
          "type": [
            "null",
            "string"
          ]
        },
        "ImplicitArguments": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/EventArgumentModel"
          }
        }
      }
    },
    "EventLevel": {
      "type": "integer",
      "x-enumNames": [
        "LogAlways",
        "Critical",
        "Error",
        "Warning",
        "Informational",
        "Verbose"
      ],
      "enum": [
        0,
        1,
        2,
        3,
        4,
        5
      ],
      "description": ""
    },
    "EventSourceSettings": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "AutogenerateLoggerInterfaces": {
          "type": "boolean"
        }
      }
    }
  }
}

=== FabricatorsGuild/FG.AutoLogger/samples/CodeEffect.ServiceFabric.Auditing/ServiceFabricServicesBackup/PersonActor/PersonActorServiceEventSource.eventsource.json
{
  "Loggers": [
    {
      "Name": "IActorDomainLogger",
      "StartId": 100,
      "ImplicitArguments": [
        {
          "Name": "actor",
          "Type": "Actor"
        },
        {
          "Name": "context",
          "Type": "ServiceRequestContext"
        }
      ],
      "OverrideArguments": []
    },
    {
      "Name": "IServiceDomainLogger",
      "StartId": 200,
      "ImplicitArguments": [
        {
          "Name": "actorService",
          "Type": "ActorService"
        },
        {
          "Name": "context",
          "Type": "ServiceRequestContext"
        }
      ],
      "OverrideArguments": []
    },
    {
      "Name": "IActorCommunicationLogger",
      "StartId": 1000,
      "ImplicitArguments": [
        {
          "Name": "actor",
          "Type": "Actor"
        }
      ],
      "OverrideArguments": [
      ]
    },
    {
      "Name": "IServiceCommunicationLogger",
      "StartId": 2000,
      "ImplicitArguments": [
        {
          "Name": "actorService",
          "Type": "ActorService"
        }
      ],
      "OverrideArguments": [
      ]
    }
  ],
  "Name": "PersonActorServiceEventSource",
  "ProviderName": "CodeEffect-ServiceFabric-Auditing-PersonActorService",
  "Keywords": [],
  "TypeTemplates": [],
  "Settings": {
    "AutogenerateLoggerInterfaces": false
  }
}

=== FabricatorsGuild/FG.AutoLogger/samples/CodeEffect.ServiceFabric.Auditing/PersonActor/PersonActorServiceEventSource.eventsource.json
{
  "Loggers": [
    {
      "Name": "IPersonActorLogger",
      "StartId": 100,
      "ImplicitArguments": [
        {
          "Name": "actor",
          "Type": "Actor"
        },
        {
          "Name": "context",
          "Type": "ServiceRequestContext"
        }
      ],
      "OverrideArguments": []
    },
    {
      "Name": "IPersonActorServiceLogger",
      "StartId": 200,
      "ImplicitArguments": [
        {
          "Name": "actorService",
          "Type": "ActorService"
        },
        {
          "Name": "context",
          "Type": "ServiceRequestContext"
        }
      ],
      "OverrideArguments": []
    },
    {
      "Name": "IServicesCommunicationLogger",
      "StartId": 1000,
      "ImplicitArguments": [
        {
          "Name": "context",
          "Type": "StatefulServiceContext"
        }
      ],
      "OverrideArguments": [
      ]
    }
  ],
  "Name": "PersonActorServiceEventSource",
  "ProviderName": "CodeEffect-ServiceFabric-Auditing-PersonActorService",
  "Keywords": [],
  "TypeTemplates": [
    {
      "Name": "ServiceRequestContext",
      "CLRType": "CodeEffect.ServiceFabric.Services.Remoting.FabricTransport.ServiceRequestContext",
      "Arguments": [
        {
          "Assignment": "CodeEffect.ServiceFabric.Services.Remoting.FabricTransport.ServiceRequestContext.Current?[\"correlationId\"]",
          "Name": "correlationId",
          "Type": "string"
        },
        {
          "Assignment": "CodeEffect.ServiceFabric.Services.Remoting.FabricTransport.ServiceRequestContext.Current?[\"userId\"]",
          "Name": "userId",
          "Type": "string"
        },
        {
          "Assignment": "CodeEffect.ServiceFabric.Services.Remoting.FabricTransport.ServiceRequestContext.Current?[\"requestId\"]",
          "Name": "requestId",
          "Type": "string"
        }
      ]
    }
  ],
  "Settings": {
    "AutogenerateLoggerInterfaces": false
  }
}

=== FabricatorsGuild/FG.AutoLogger/samples/Application Insights for Service Fabric/StatelessRunnerService/DefaultEventSource.eventsource.json
{
  "Loggers": [
    {
      "Name": "IStatelessRunnerServiceLogger",
      "StartId": 1000,
      "ImplicitArguments": [
        {
          "Name": "context",
          "Type": "ServiceContext"
        }
      ],
      "OverrideArguments": []
    }
  ],
  "Name": "DefaultEventSource",
  "ProviderName": "StatelessRunnerService-Default",
  "Keywords": [],
  "TypeTemplates": [
    {
      "Name": "Process",
      "CLRType": "System.Diagnostics.Process",
      "Arguments": [
        {
          "Name": "processId",
          "Type": "int",
          "Assignment": "$this.ProcessId"
        }
      ]
    },
    {
      "Name": "Exception",
      "CLRType": "System.Exception",
      "Arguments": [
        {
          "Name": "message",
          "Type": "string",
          "Assignment": "$this.Message"
        },
        {
          "Name": "source",
          "Type": "string",
          "Assignment": "$this.Source"
        },
        {
          "Name": "exceptionTypeName",
          "Type": "string",
          "Assignment": "$this.GetType().FullName"
        },
        {
          "Name": "exception",
          "Type": "string",
          "Assignment": "$this.AsJson()"
        }
      ]
    },
    {
      "Name": "ServiceContext",
      "CLRType": "System.Fabric.ServiceContext",
      "Arguments": [
        {
          "Assignment": "$this.ServiceName.ToString()",
          "Name": "serviceName",
          "Type": "string"
        },
        {
          "Assignment": "$this.ServiceTypeName",
          "Name": "serviceTypeName",
          "Type": "string"
        },
        {
          "Assignment": "$this.GetReplicaOrInstanceId()",
          "Name": "replicaOrInstanceId",
          "Type": "long"
        },
        {
          "Assignment": "$this.PartitionId",
          "Name": "partitionId",
          "Type": "Guid"
        },
        {
          "Assignment": "$this.CodePackageActivationContext.ApplicationName",
          "Name": "applicationName",
          "Type": "string"
        },
        {
          "Assignment": "$this.CodePackageActivationContext.ApplicationTypeName",
          "Name": "applicationTypeName",
          "Type": "string"
        },
        {
          "Assignment": "$this.NodeContext.NodeName",
          "Name": "nodeName",
          "Type": "string"
        }
      ]
    }
  ],
  "Settings": {
    "AutogenerateLoggerInterfaces": false
  }
}

=== FabricatorsGuild/FG.AutoLogger/samples/CodeEffect.ServiceFabric.Auditing/TitleService/TitleActorServiceEventSource.eventsource.json
{
  "Loggers": [
    {
      "Name": "ITitleServiceLogger",
      "StartId": 200,
      "ImplicitArguments": [
        {
          "Name": "serviceContext",
          "Type": "StatefulServiceContext"
        },
        {
          "Name": "requestContext",
          "Type": "ServiceRequestContext"
        }
      ],
      "OverrideArguments": []
    },
    {
      "Name": "ICommunicationLogger",
      "StartId": 1000,
      "ImplicitArguments": [
        {
          "Name": "context",
          "Type": "StatefulServiceContext"
        }
      ],
      "OverrideArguments": [
      ]
    }
  ],
  "Name": "TitleServiceEventSource",
  "ProviderName": "CodeEffect-ServiceFabric-Auditing-TitleService",
  "Keywords": [],
  "TypeTemplates": [],
  "Settings": {
    "AutogenerateLoggerInterfaces": false,
    "Modules": [ "ServiceFabric", "AI" ]
  }
}

=== FabricatorsGuild/FG.AutoLogger/samples/CodeEffect.ServiceFabric.Auditing/WebApiService/WebApiServiceEventSource.eventsource.json
{
  "Loggers": [
    {
      "Name": "IWebApiLogger",
      "StartId": 100,
      "ImplicitArguments": [
        {
          "Name": "context",
          "Type": "StatelessServiceContext"
        }
      ]
    },
    {
      "Name": "ICommunicationLogger",
      "StartId": 200,
      "ImplicitArguments": [
        {
          "Name": "context",
          "Type": "StatelessServiceContext"
        }
      ]
    },
    {
      "Name": "IOwinCommunicationLogger",
      "StartId": 300,
      "ImplicitArguments": [
        {
          "Name": "context",
          "Type": "StatelessServiceContext"
        }
      ]
    },
    {
      "Name": "IServiceHostLogger",
      "StartId": 400
    }
  ],
  "Name": "WebApiServiceEventSource",
  "ProviderName": "CodeEffect-ServiceFabric-Auditing-WebApi",
  "Keywords": [],
  "TypeTemplates": [
  ],
  "Settings": {
    "AutogenerateLoggerInterfaces": false,
    "Modules": [ "ServiceFabric", "AI" ]
  }
}

=== FabricatorsGuild/FG.AutoLogger/samples/CodeEffect.ServiceFabric.Auditing/CodeEffect.ServiceFabric.Diagnostics/DefaultEventSource.eventsource.json
{
  "Loggers": [],
  "Name": "DefaultEventSource",
  "ProviderName": "CodeEffect-ServiceFabric-Actors-FabricTransport-Diagnostics-Default",
  "Keywords": [],
  "TypeTemplates": [
    {
      "Name": "Exception",
      "CLRType": "System.Exception",
      "Arguments": [
        {
          "Name": "message",
          "Type": "string",
          "Assignment": "$this.Message"
        },
        {
          "Name": "source",
          "Type": "string",
          "Assignment": "$this.Source"
        },
        {
          "Name": "exceptionTypeName",
          "Type": "string",
          "Assignment": "$this.GetType().FullName"
        },
        {
          "Name": "exception",
          "Type": "string",
          "Assignment": "$this.AsJson()"
        }
      ]
    }
  ],
  "Settings": {
    "AutogenerateLoggerInterfaces": false
  }
}
